name: Deploy backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github-actions-deploy
          chmod 600 ~/.ssh/github-actions-deploy

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/github-actions-deploy \
            -o StrictHostKeyChecking=no \
            ubuntu@${{ secrets.EC2_HOST }} \
            "whoami"

































# name: Deploy backend

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Set up SSH
#         run: |
#           mkdir -p ~/.ssh

#       - name: Set up SSH key
#         run: |
#           echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github-actions-deploy
#           chmod 600 ~/.ssh/github-actions-deploy           